name: Get and Cache Dependencies
description: Get the NodeJS dependencies and cache them.
runs: 
  using: composite
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ex1/node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ./ex1
      run: npm ci
      shell: bash