name: Ex1 On Commit
on: push
jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code from repo.
        uses: actions/checkout/@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./ex1
        run: npm ci
      - name: Run scripts
        working-directory: ./ex1
        run: |
          npm run lint
          npm run test
          npm run build
